resource:
  mysql:
    host: 127.0.0.1
    port: 3306
  redis:
    host: 127.0.0.1
    port: 6379
  influxdb:
    host: 192.168.1.151
    port: 8086


amdb:
  out:
    url: 127.0.0.1:10032
pradar:
  out:
    url: 192.168.0.61:8090

data.path: /

# agent交互的zk地址
takin.config.zk.url: 192.168.1.154:2181,192.168.1.154:2181,192.168.1.154:2181
spring:
  datasource:
    password: shulie#Poy6Y8
  config:
    whiteListPath: /Users/hezhongqi/shulie
#  flyway:
#    enabled: false
#  redis:
#    sentinel:
#      # 主节点的别名
#      master: mymaster
#      # sentinel服务的ip和端口
#      nodes: 192.168.1.120:29001,192.168.1.120:29002,192.168.1.120:29003
#    host:

env: local


takin-cloud:
  out:
    url: 192.168.1.71
#    port: ""

### 登录通知推送钉钉 prod配置
login:
  dingding:
    push:
      enable: false
      url: https://oapi.dingtalk.com/robot/send?access_token=7ff71ca59b08340b5b07a146b053527eebb4f834856380d2c33f5a1d6fcd3bb8


#mybatis-plus.configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# amdb
#logging.level.io.shulie.takin.web.app.service.amdb: WARN
# takin-web-data-dao
#logging.level.io.shulie.takin.web.data.dao: DEBUG

takin:
  license: 5b06060a-17cb-4588-bb71-edd7f65035af